# Generated by Django 3.0 on 2022-11-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status_name',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
