# Generated by Django 3.0 on 2022-11-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20221121_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='simorder',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.OrderStatus'),
            preserve_default=False,
        ),
    ]
