# Generated by Django 3.0 on 2022-11-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_simorder_sim_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='registration.Gift'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='registration.OrderStatus'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='registration.Client'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='sim_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_types', to='registration.SimCardOption'),
        ),
    ]
