# Generated by Django 3.0 on 2022-12-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20221130_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_picture', models.ImageField(default='default.jpg', upload_to='images/message')),
            ],
        ),
    ]
