# Generated by Django 3.0 on 2022-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_messagetouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetouser',
            name='message_picture',
            field=models.ImageField(default='default.jpg', upload_to='images/message/'),
        ),
    ]
