# Generated by Django 3.0 on 2022-12-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20221210_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simorder',
            name='id_picture',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='simorder',
            name='id_picture2',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
